using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
namespace fantasyapp
{
    public class Writer
    {
        public static void Write(string name)
        {
            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;

            XmlWriter writer = XmlWriter.Create("Player.xml", settings);
            writer.WriteStartDocument();
            writer.WriteComment("this file is generated by the program");
            writer.WriteStartElement("Player");
            writer.WriteElementString("Name", name); //name is passed in from the argument in the form
            writer.WriteEndElement();
            writer.WriteEndDocument();


            writer.Flush();
            writer.Close();
        }
    }
}
